# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8ad9cc469e1fd7b5c137552611722bd66fbca11a24acad608880fa39eaf222260892beef433eb2dce87198a51de70735bfcccfc90da4a609e353071b667130b7

test:
  secret_key_base: 3da16d1e8c655941e67110dccf79784e83bb911f2ac8c43f7d558c01ff8cf8bb9c78a86087acf1f5c40bf2a1d803ab15522563e5fa99ffbb9a9699e9c26224a5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
